check for devtab

diff --git a/lxc-dev-create b/lxc-dev-create
--- a/lxc-dev-create
+++ b/lxc-dev-create
@@ -3,6 +3,11 @@
 devtab=$1
 devdir=$2
 
+if ! [ -f "${devtab}" ]; then
+	echo "ERROR: device table $devtab does not exist." >&2
+	exit 1
+fi
+
 if ! [ -d "${devdir}" ]; then
 	echo "ERROR: directory $devdir does not exist." >&2
 	exit 1
diff --git a/lxc-dev-perms b/lxc-dev-perms
--- a/lxc-dev-perms
+++ b/lxc-dev-perms
@@ -2,6 +2,11 @@
 
 devtab=$1
 
+if ! [ -f "${devtab}" ]; then
+	echo "ERROR: device table $devtab does not exist." >&2
+	exit 1
+fi
+
 egrep -v '^#|^$' ${devtab} |
 while read dev type major minor mode; do
 	case $type in
